name = "inward-outward-client"
compatibility_date = "2024-02-03"
# main = "worker/src/index.js" # Removed to prevent worker build

# Wait, for purely static assets on Workers, we might need no main?
# The error says "Missing entry-point to Worker script OR to assets directory". 
# Providing assets directory should be enough.

[assets]
directory = "./dist"
binding = "ASSETS"
